# Common aliases
# Sourced by both .zshrc and .bashrc

# Directory navigation
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias cd-='cd -'

# List directory
alias l='ls -lh'
alias la='ls -lah'
alias ll='ls -lh'
alias ls='ls -G'

# Navigation shortcuts
alias home='cd ~'
alias dotfiles='cd "$DOTFILES_ROOT"'
alias desk='cd ~/Desktop'
alias docs='cd ~/Documents'
alias dl='cd ~/Downloads'

# Editing
alias v='nvim'
alias vi='nvim'
alias vim='nvim'
alias e='$EDITOR'

# Git shortcuts
alias g='git'
alias ga='git add'
alias gaa='git add --all'
alias gam='git add --modified'
alias gau='git add --update'
alias gb='git branch'
alias gbd='git branch --delete'
alias gbD='git branch --delete --force'
alias gbl='git branch --list'
alias gbm='git branch --move'
alias gbnm='git branch --no-merged'
alias gbr='git branch --remote'
alias gbs='git branch --show-current'
alias gc='git commit'
alias gcm='git commit --message'
alias gco='git checkout'
alias gcob='git checkout -b'
alias gcod='git checkout develop'
alias gcom='git checkout main'
alias gcp='git cherry-pick'
alias gcpa='git cherry-pick --abort'
alias gcpc='git cherry-pick --continue'
alias gd='git diff'
alias gda='git diff --cached'
alias gdh='git diff HEAD~1'
alias gds='git diff --staged'
alias gdt='git diff --tool'
alias gf='git fetch'
alias gfa='git fetch --all'
alias gfo='git fetch origin'
alias gl='git log'
alias glo='git log --oneline'
alias glod='git log --oneline develop'
alias glom='git log --oneline main'
alias gm='git merge'
alias gma='git merge --abort'
alias gmc='git merge --continue'
alias gmm='git merge main'
alias gmnff='git merge --no-ff'
alias gp='git push'
alias gpd='git push origin --delete'
alias gpo='git push origin'
alias gpod='git push origin develop'
alias gpom='git push origin main'
alias gpr='git push --recurse-submodules'
alias gpu='git push --set-upstream'
alias gpo='git pull origin'
alias gpom='git pull origin main'
alias gpod='git pull origin develop'
alias gr='git rebase'
alias gra='git rebase --abort'
alias grc='git rebase --continue'
alias gri='git rebase --interactive'
alias grim='git rebase --interactive main'
alias grs='git rebase --skip'
alias grem='git remote'
alias grema='git remote add'
alias gremr='git remote remove'
alias gremv='git remote --verbose'
alias gs='git status'
alias gsh='git show'
alias gst='git stash'
alias gsta='git stash apply'
alias gstc='git stash clear'
alias gstd='git stash drop'
alias gstl='git stash list'
alias gstp='git stash pop'
alias gsts='git stash show --text'
alias gt='git tag'
alias gtd='git tag --delete'
alias gtl='git tag --list'

# System utilities
alias sudo='sudo '
alias cp='cp -i'
alias mv='mv -i'
alias rm='rm -i'
alias mkdir='mkdir -p'

# Networking
alias ip='curl -s https://ifconfig.me && echo'
alias localip='ipconfig getifaddr en0 2>/dev/null || ifconfig | grep "inet " | grep -v 127.0.0.1'

# Disk usage
alias df='df -h'
alias du='du -h'
alias dus='du -sh *'

# Environment
alias reload='exec $SHELL -l'
alias editconfig='$EDITOR ~/.zshrc'
alias src='source ~/.zshrc'
